server:
  port: 9052

spring:
  application:
    name: config-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#将/actuator/refresh这个 Endpoint 暴露出来
management:
  endpoints:
    web:
      exposure:
        include: "*"


