server:
  port: 9001

spring:
  application:
    name: eureka-server

eureka:
  #eureka实例名，集群中根据这里相互识别
  instance:
    hostname: eureka-a
    #续约时间
    lease-expiration-duration-in-seconds: 90
    #定时任务时间，每隔多少秒去重新刷新续约时间
    lease-renewal-interval-in-seconds: 30
  #客户端
  client:
    #是否开启注册服务，无需自己注册自己
    register-with-eureka: true
    #是否拉取服务列表
    fetch-registry: true
    #注册中心地址,实现高可用
    service-url:
      defaultZone: http://eureka-b:9002/eureka/, http://eureka-c:9003/eureka/
  server:
    #是否开启安全保护，默认是开启的，如果默认开启，注册中心的服务列表就算有些服务断开了，也会继续保存
    enable-self-preservation: false