server:
  port: 9031

spring:
  application:
    name: feign-invoke

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka/

#开启 Hystrix 功能
feign:
  circuitbreaker:
    enabled: true
