server:
  port: 9630

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。
      #默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
      discovery:
        locator:
          enabled: true
      #默认过滤器，对所有的路由都有效
      default-filters:
      routes:
        - id: gateway-one
          uri: lb://CONSUMER-CLIENT-B
          order: 0
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1



eureka:
  client:
    service-url:
      defaultZone: http://localhost:9003/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug