server:
  port: 9072

spring:
  application:
    name: consul-provider
  cloud:
    consul:
      #consul服务器的主机地址
      host: localhost
      #consul服务器的端口
      port: 8500
      discovery:
        #是否需要注册
        register: true
        #服务的名称
        service-name: ${spring.application.name}
        #注册的实例ID (唯一标志)
        instance-id: ${spring.application.name}-1
        #当前服务的请求ip
        ip-address: ${spring.cloud.client.ip-address}
        #指定开启ip地址注册
        prefer-ip-address: true
        #健康检查
        health-check-path: /actuator/health
        #服务健康检查时间（每10秒一次）
        health-check-interval: 10s
        #服务请求端口
        port: ${server.port}
